### PR TITLE
fix(app): Adjust positions of buttons & legend in CPC and uninstall deprecated dependency

### PR DESCRIPTION
**Pull request by mansnym**
Not an ideal solution but I think it's better than only seeing half of the hierarchy display. Tried to make the legend stick to the right hand side of the svg but I couldn't get it to stay in a fixed position on window resizing (my css skills are non-existent) so this is the best I could do.

### CODE REVIEW

**Comment by ernum** [comment]
Looks good, but I think it could be very on small devices. Maybe @Hymalide can send a screenshot of how it looks?

**Comment by Hymalide** [comment]
https://drive.google.com/file/d/1EtvXy6vCZEef2O1byOWSJ73JfpowtG-n/view?usp=sharing

How it looks on my screen

**Comment by mansnym** [comment]
> https://drive.google.com/file/d/1EtvXy6vCZEef2O1byOWSJ73JfpowtG-n/view?usp=sharing
> 
> How it looks on my screen

Still better than what we currently have

**Review by ernum — APPROVED** [review]
LGTM

**Pull request merged**
