### PR TITLE
table+video components

### PR DESCRIPTION
**Pull request by modi-99**

### CODE REVIEW

**Review by mansnym — APPROVED** [review]

**Comment by mansnym** [comment]
I would still like to see some improvements but I might just be nitpicking at this point... Would love that invisible scroll bar Marine found and also make the video view rescale the same way as the circle chart does. I.e. make it smaller and smaller on window downsizing but always fill the whole div. But given the time situation I won't be causing any more fuss:)

**Review by ernum — COMMENTED** [review]
Preview isn't working atm. Is that intentional?

**Comment by mansnym** [comment]
> Preview isn't working atm. Is that intentional?

No it looks like this happened after Marine merged main into this branch

**Comment by modi-99** [comment]
> > Preview isn't working atm. Is that intentional?
> 
> No it looks like this happened after Marine merged main into this branch

yes no, i dont know what happend really

**Comment by mansnym** [comment]
Just had a look and she removed the button to switch in the merge hehe

**Comment by mansnym** [comment]
> yes no, i dont know what happend really

Revert to your latest commit, resolve the merge conflicts and then merge into main

**Comment by mansnym** [comment]
I reverted the merge made by Marine and resolved the merge conflicts in a separate branch and pushed it and opened a new PR.

**Pull request closed without merging**
