### PR TITLE
feat(app): Add (de)select functionality and update circle chart tooltip

### PR DESCRIPTION
**Pull request by ernum**

### CODE REVIEW

**Review by mansnym — COMMENTED** [review]
In general looks good but I found a couple of things that should be fixed: 

- Selected exercises lose their outline stroke in the CP chart when you move your mouse around. After switching sorting scheme or selecting/deselecting muscles they all have their outlines but as soon as mouse is moved they are removed. 
- The placement of the BodySection tooltips have been changed (moved up by quite a bit).

I don't mind fixing the formatting but it would be a lot easier to help out with debugging if the formatting fixes were committed separately (so I don't have to check for changes over 700 lines hehe)

**Comment by ernum** [comment]
> In general looks good but I found a couple of things that should be fixed:
> 
> * Selected exercises lose their outline stroke in the CP chart when you move your mouse around. After switching sorting scheme or selecting/deselecting muscles they all have their outlines but as soon as mouse is moved they are removed.
> * The placement of the BodySection tooltips have been changed (moved up by quite a bit).
> 
> I don't mind the format fixing but it would be a lot easier for me to help out with debugging if they were committed separately (so I don't have to check for changes over 700 lines hehe)

Yeah, you're completely right on the formatting thing. Will merge with main after [this](https://github.com/ernum/Vizercise/pull/59) is approved.

**Comment by mansnym** [comment]
> Yeah, you're completely right on the formatting thing. Will merge with main after [this](https://github.com/ernum/Vizercise/pull/59) is approved. I've also resolved the issues you mentioned.

Nice one! Format fix pr is merged. Just had a look and the issues seem very much resolved indeed. Noticed a couple of other things tho...

- On mouseover on exercses in CP chart, the tooltip first appears for a brief moment in the top left corner of the CP chart div / outerSvg before appearing where it should. Could probably just be adjusted by setting it to visible first when it is at its correct location(?) 
- This is a super minor thing and I'm not even sure it's something we would like to change but I'll mention it anyway: The layout of the CP chart is slightly different (exercises appear in other places) when you hit the select all muscles button. Feel like I could come up with arguments both for keeping it this way and for changing it so I'm not really sure if we ought to change it.

**Comment by mansnym** [comment]
I also just realized that with these features added, perhaps it would actually make sense to make it so that 0 muscles selected --> 0 exercises shown. Instead of showing all exercises by default, show something similar to what is shown for the table when nothing is selected, e.g. "please select a muscle". Not something we need to do now I suppose but pr comment sections are as good a place as any to scribble down my thoughts and ideas (or are they...)

**Comment by ernum** [comment]
> I also just realized that with these features added, perhaps it would actually make sense to make it so that 0 muscles selected --> 0 exercises shown. Instead of showing all exercises by default, show something similar to what is shown for the table when nothing is selected, e.g. "please select a muscle". Not something we need to do now I suppose but pr comment sections are as good a place as any to scribble down my thoughts and ideas (or are they...)

Definitely agree with this. But, best we don't make big changes now IMO since Mario seems to be happy with it as is.

**Comment by mansnym** [comment]
>     1. I can't replicate the issue you had with the tooltip on a consistent enough basis to fix it. Can you do so?
> 
>     2. Yeah, I noticed this as well. I think keeping it consistent is the best solution so I've fixed it to not change.

1.  Where the tooltip first appears.

tooltiptopleft

After moving the mouse a little bit but still mousing over the same exercise, the tooltip is correctly displayed.

tooltipcorrect

2. Sounds good! 
3. Agree on the last comment.

**Comment by ernum** [comment]
> > ```
> > 1. I can't replicate the issue you had with the tooltip on a consistent enough basis to fix it. Can you do so?
> > 
> > 2. Yeah, I noticed this as well. I think keeping it consistent is the best solution so I've fixed it to not change.
> > ```
> 
> 1. Where the tooltip first appears.
> 
> tooltiptopleft
> 
> After moving the mouse a little bit but still mousing over the same exercise, the tooltip is correctly displayed.
> 
> tooltipcorrect
> 
> 2. Sounds good!
> 3. Agree on the last comment.

Still can't get the problem consistently but I think it should be solved now. I don't like the solution but if there's no lag (let me know if you think there is) I think we can keep it.

**Comment by carterwsmith** [comment]
This breaks a lot of things for me when applying filters

**Comment by carterwsmith** [comment]
to be more specific, it removes the transition and makes it impossible to apply / transition between multiple filters at once

**Comment by ernum** [comment]
> > Still can't get the problem consistently but I think it should be solved now. I don't like the solution but if there's no lag (let me know if you think there is) I think we can keep it.
> 
> I mean there is some lag (current main is smoother for sure) but I don't think it has gotten worse since you first opened this pr. Apart from the lag increase, the issue with this solution (as I'm guessing you've also noticed) is that the tooltip doesn't appear right away. If I quickly move my mouse over an exercise in the CP chart and don't move the mouse again, the exercise gets an outline but the tooltip doesn't show. Moving the mouse slightly but still having it over said exercise makes the tooltip appear. Running out of time to fix stuff at this point tho so I dunno if we just say f it at this point perhaps. What do you think?
> 
> Edit: Forgot to confirm that the original issue (tooltip first appearing in top left corner of CP chart div) is indeed resolved.

The lag should be significantly less now. Can you confirm whether it's true on your end? The tooltip not appearing right away is an issue prior to the changes I've made. Think we can let this be since Mario did not comment on it. The other issues should be resolved as well (they are on my end at least).

**Comment by ernum** [comment]
> to be more specific, it removes the transition and makes it impossible to apply / transition between multiple filters at once

Nice catch; this issue is solved now.

**Comment by mansnym** [comment]
> > > Still can't get the problem consistently but I think it should be solved now. I don't like the solution but if there's no lag (let me know if you think there is) I think we can keep it.
> > 
> > 
> > I mean there is some lag (current main is smoother for sure) but I don't think it has gotten worse since you first opened this pr. Apart from the lag increase, the issue with this solution (as I'm guessing you've also noticed) is that the tooltip doesn't appear right away. If I quickly move my mouse over an exercise in the CP chart and don't move the mouse again, the exercise gets an outline but the tooltip doesn't show. Moving the mouse slightly but still having it over said exercise makes the tooltip appear. Running out of time to fix stuff at this point tho so I dunno if we just say f it at this point perhaps. What do you think?
> > Edit: Forgot to confirm that the original issue (tooltip first appearing in top left corner of CP chart div) is indeed resolved.
> 
> The lag should be significantly less now. Can you confirm whether it's true on your end? The tooltip not appearing right away is an issue prior to the changes I've made. Think we can let this be since Mario did not comment on it. The other issues should be resolved as well (they are on my end at least).

I haven't seen that issue before but it doesn't really matter cus it's gone now heheee. Looks great my guy, nicely done!

**Comment by mansnym** [comment]
I'm down to approve but I just want to double check: Do we want to show tooltips for nodes that are not leafs? Don't quote me on this but I thought that you were against this idea when I first brought it up after Mario's feedback on the matter? I'm fine with either option, just want to make sure nothing is overlooked

**Comment by carterwsmith** [comment]
> I'm down to approve but I just want to double check: Do we want to show tooltips for nodes that are not leafs? Don't quote me on this but I thought that you were against this idea when I first brought it up after Mario's feedback on the matter? I'm fine with either option, just want to make sure nothing is overlooked

Based on Mario's feedback we agreed to not do this--  keep it consistent by only showing tooltips for exercises

**Comment by mansnym** [comment]
> > I'm down to approve but I just want to double check: Do we want to show tooltips for nodes that are not leafs? Don't quote me on this but I thought that you were against this idea when I first brought it up after Mario's feedback on the matter? I'm fine with either option, just want to make sure nothing is overlooked
> 
> Based on Mario's feedback we agreed to not do this-- keep it consistent by only showing tooltips for exercises

Well, Mario's feedback was that he thought we should use tooltips for everything (thus making it consistent with showing tooltips for exercises). But as you say, despite Mario's input, we agreed to use tooltips only for exercises (also keeping it consistent, just in a different way 😄 )

**Comment by ernum** [comment]
Yeah, you guys are right. Didn't even notice that change. Should be updated now.

**Comment by mansnym** [comment]
> Yeah, you guys are right. Didn't even notice that change. Should be updated now.

It is, looks great! 💯

**Pull request merged**
