### PR TITLE
feat(app): Add header and favicon

### PR DESCRIPTION
**Pull request by ernum**

### CODE REVIEW

**Comment by mansnym** [comment]
Is something supposed to be showing? The title leads me to believe I'd see a header but I don't see anything

**Comment by ernum** [comment]
> Is something supposed to be showing? The title leads me to believe I'd see a header but I don't see anything

Not on the website. See following:
image

**Comment by mansnym** [comment]
Now that is some fancy stuff my good sir.

**Review by mansnym — APPROVED** [review]
This is the mic drop, your attention to detail is unmatched!

**Pull request merged**
