### PR TITLE
feat(app): Add about us popup page & project title

### PR DESCRIPTION
**Pull request by Hymalide**
Logo was added with font
About us button was added
Pop Up page for the About us button was created
Text was added to it

Last thing to be done after merge: font update on About Us oage (I don't have the font file on this branch)

### CODE REVIEW

**Review by mansnym — COMMENTED** [review]
Good job! Some feature related things I would like to see adjusted:

- Push the main screen divs up a little bit (make them more centered basically)
- Update project responsibilities 
- Make the right edge of the about us popup rounded.

There are also some file additions and edits which I don't think should be included:

- CirclePacking.js does not need to be included (only 2 blank rows added)
- ExerciseDetail.js does not need to be included (only 1 blank row added)
- vizercise/.vs should not be included
- vizercise/config should not be included(?)
- vizercise/v16 should not be included(?)

**Comment by Hymalide** [comment]
Instruction unclear, I did not do what I intended and had to revert the changes, I have no idea how to remove files from a pull request

**Comment by Hymalide** [comment]
> Logo was added with font About us button was added Pop Up page for the About us button was created Text was added to it
> 
> Last thing to be done after merge: font update on About Us page (I don't have the font file on this branch)

Font update is done with the last merge thanks to Ernest's clean work

**Comment by mansnym** [comment]
> Instruction unclear, I did not do what I intended and had to revert the changes, I have no idea how to remove files from a pull request

For edited files: open them and restore them to their previous state (ctrl+z should do the trick, otherwise just compare changes).
For added files: remove them from your local branch.
Once above instructions are complete -> commit & push

**Comment by mansnym** [comment]
Regarding the div centering, I think I see the problem. The project title should probably be set to rescale and flex the same way as the divs do to make it look good on all screen resolutions.

**Review by mansnym — COMMENTED** [review]
asdf
asdf
asdf
asdf

**Review by mansnym — COMMENTED** [review]
Title and about us button are still not flexing. The invisible scroll bar is very much visible on my screen but is on the left side instead of on the right side now. The file slnx.sqlite in visercise/.vs should also not be included

**Comment by Hymalide** [comment]
> Title and about us button are still not flexing. The invisible scroll bar is very much visible on my screen but is on the left side instead of on the right side now. The file slnx.sqlite in visercise/.vs should also not be included

Can I have a screenshot please ?

**Review by mansnym — APPROVED** [review]
Flexing of title and about us button is much better now and probably as good as it will get. I still see the scroll bar but it seems to be browser related so let's go ahead and merge. Good job!

**Pull request merged**
